CREATE TABLE IF NOT EXISTS stocks (
  prize_id      INT UNSIGNED PRIMARY KEY,
  initial_qty   INT UNSIGNED NOT NULL,
  remaining_qty INT UNSIGNED NOT NULL,
  daily_limit   INT UNSIGNED DEFAULT NULL,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (prize_id) REFERENCES prizes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
